In [2]:
import numpy as np

Use the arrage function to generat the array

In [3]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

You can use the index to select the slice

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

You can reassign the value to array

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Use the equal operator is not a copy, it is a reference

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

so when the slice_of_arr is updated to 99, the arr[0:6] is changed too

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

So you should use copy() to do the copy operation

In [17]:
arr = np.arange(0,11)

In [20]:
copy_of_arr = arr.copy()

In [25]:
copy_of_arr[:] = 99

In [26]:
copy_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])